# Generated by Django 2.1.2 on 2018-11-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de  Início')),
                ('image', models.ImageField(upload_to='courses/images', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Editado em ')),
            ],
        ),
    ]
