# Generated by Django 2.1.2 on 2019-01-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20181221_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_model',
            field=models.TextField(blank=True, verbose_name='Test'),
        ),
    ]
