# Generated by Django 2.1.2 on 2019-01-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_test_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='test_model',
        ),
    ]
